import type { Metadata } from 'next'
import { Inter as MainFont } from 'next/font/google'
import './globals.css'

import { cn } from "@/lib/utils"
const mainFont = MainFont({ 
  subsets: ["latin"],
  variable: "--font-sans",
})

//add config for a body font if necessary

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={
        cn(
          "min-h-screen bg-background font-sans antialiased",
          mainFont.variable
        )
      }>{children}</body>
    </html>
  )
}
